### ISSUE TITLE
What are "components" in as.antsImage?

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#10]
In the code, it says `components = FALSE`, but in the help it says
```
components	number of components per voxel, e.g. 1
```
and even when you put in a reference, the `components` are set to 
```r
components = (reference@components > 1)
```
where it will become a logical `FALSE` in most cases.

**Comment by stnava** [comment]
components should be 

```
components	number of components per voxel, e.g. 1
```

but there may be some reason @jeffduda  sets to `FALSE` when there is only scalar data.

this may control the underlying cpp type.

**Comment by jeffduda** [comment]
The "isVector" boolean was added to handle the case of a one-component
vector image and how that is recognized in the cpp wrappers.
