### ISSUE TITLE
LabelOverlapMeasures added

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#104]
I think adding https://github.com/ANTsX/ANTs/blob/master/Examples/LabelOverlapMeasures.cxx would be a great addition to the ANTsRCore package.  I need Hausdorff distance for some of my research and it seems like https://github.com/ANTsX/ANTs/issues/611 has indicated that this should be fixed, but https://github.com/ANTsX/ANTs/commit/295ae80b84e29950cb32ab4166ec9822d7d13cc5 had the hausdorff distance, but it seemed it was immediately removed from @ntustison in https://github.com/ANTsX/ANTs/commit/119dd3bebe2a401463f9bbff719a6deab44df1e4#diff-267dd586075f89a331c8b476d18fe752

**Describe the solution you'd like**
LabelOverlapMeasures.cpp for overlap measures (including Hausdorff and ASD)

**Describe alternatives you've considered**
You can do this in R, but seems like the ITK functionality is more optimized for this function.

**Comment by ntustison** [comment]
I removed the code because of a [pre-existing class](https://itk.org/Doxygen/html/classitk_1_1HausdorffDistanceImageFilter.html) for calculating the Hausdorff distance.  It would be easy to include that class, if needed.

**Comment by muschellij2** [comment]
I see.  I'm looking but, it is possible to calculate Hausdorff or ASD in
ANTsRCore?  I'm not against trying to adapt this code, but I'm not as
familiar with the ANTs codebase to figure out what the easiest path to
doing this.  Any guidance would be appreciated
Best,
John

**Comment by muschellij2** [comment]
Regardless, can close but would be interested in the discussion.

**Comment by stnava** [comment]
in brief:

```
max( iMath( segmentation, "D" ) * segmentation )
```

something like this.

**Comment by stnava** [comment]
```
hausdorffDistance <- function( binarySeg1, binarySeg2 ) {
  d1 = iMath( binarySeg1, "D" ) * binarySeg2
  d2 = iMath( binarySeg2, "D" ) * binarySeg1
  return( max( c( max( abs( d1 ) ), max( abs( d2 ) ) ) ) )
}
seg1 = thresholdImage( ri( 1 ), "Otsu", 3 ) %>% thresholdImage( 2, 2 )
seg2 = thresholdImage( ri( 2 ), "Otsu", 3 ) %>% thresholdImage( 2, 2 )
seg5 = thresholdImage( ri( 5 ), "Otsu", 3 ) %>% thresholdImage( 2, 2 )
hausdorffDistance( seg1, seg2 )
hausdorffDistance( seg1, seg5 )
```

probably close to correct

**Comment by stnava** [comment]
note update - need `MaurerDistance` because it gives signed distance.
