### ISSUE TITLE
Question about contributing code

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsRCore#127]
I'm currently trying to add an additional N3 bias correction [variant](https://github.com/ANTsX/ANTsRCore/pull/126) which exposes additional parameters.  However, I'm running into a problem when running ``roxygen2::roxygenise()``.  I currently get the following:

```
> roxygen2::roxygenise()
Loading ANTsRCore
unloadNamespace("ANTsRCore") not successful, probably because another loaded package depends on it. Forcing unload. If you encounter problems, please restart R.
Creating a new generic function for ‘max’ in package ‘ANTsRCore’
Creating a new generic function for ‘min’ in package ‘ANTsRCore’
Creating a new generic function for ‘range’ in package ‘ANTsRCore’
Creating a new generic function for ‘prod’ in package ‘ANTsRCore’
Creating a new generic function for ‘sum’ in package ‘ANTsRCore’
Creating a new generic function for ‘any’ in package ‘ANTsRCore’
Error in (get(".Internal", baseenv()))(delayedAssign(x, value, eval.env,  : 
  cannot change value of locked binding for 'iMathOps'
```

I checked the current master branch and it would seem that this problem exists there as well.  Has anybody seen this before and potentially provide a solution?

**Comment by muschellij2** [comment]
Did you Restart R?  The line indicates that ANTsRCore was loaded:
unloadNamespace("ANTsRCore") not successful, probably because another
loaded package depends on it. Forcing unload. If you encounter problems,
please restart R.
Best,
John

**Comment by ntustison** [comment]
Brilliant, @muschellij2 .  I had restarted R but your comment made me realize that I was loading "ANTsR" in my .Rprofile.  Once I took that out, everything was fine.  Thanks.
