### ISSUE TITLE
Blob Detector fails with multi-threading

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsRCore#129]
**Describe the bug**

Multi-threading in the multi scale laplacian blob detector broken.

This commit https://github.com/ANTsX/ANTsRCore/commit/3dd62669850690afa59250e6f38bc68dc7526926 will support debugging.  As a temporary measure, I added a file called `itkMultiScaleLaplacianBlobDetectorImageFilter2.[h,hxx]` to the src directory which is a slightly modified copy of the file `itkMultiScaleLaplacianBlobDetectorImageFilter.[h,hxx]` in ANTs.  This supports quicker turn-around of the build/test cycle but would ultimately be removed if the original ANTs version of the code gets fixed.

I also tried to annotate locations of likely issues with `FIXME` in the above `hxx`.

**To Reproduce**

In `.Renviron`   set  `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1` and run below code.

Do the same thing with `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=2` and we get a segfault.

```
library(ANTsRCore)
blob2 = scaleSpaceFeatureDetection( max( ri( 1 ) ) - ri( 1 ), 50 )
plot( ri(1), iMath( blob2$blobImage, "GD", 5 ) )
```

**Expected behavior**

Either 

1. enforce single-threaded execution in this filter 

or 

2. repair the multi-threaded execution

**Comment by stnava** [comment]
Additional information:  https://github.com/blowekamp/itkScaleSpace

**Comment by stnava** [comment]
@ntustison - this is fixed now but we should probably work these changes back into ants ... will do later.

**Comment by ntustison** [comment]
Awesome.  This is great.
