### ISSUE TITLE
The download failure

### ISSUE THREAD

**Issue by yangwei1993** [ANTsX/ANTsRCore#145]
**Describe the bug**
the download website could not be opened

**To Reproduce**
1. click the download link in the different version

**Expected behavior**

**Session Info**

Please include output from `R` of:
```r
ANTsRCore::antsVersions
sessioninfo::session_info("ANTsRCore")
````

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stnava** [comment]
unclear issue - closing
