### ISSUE TITLE
Binary builds

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#30]
So I cannot get the timings down to < 50 mins for Mac on Travis.  I built the binaries on my machine:
```
OSX: 10.12.6 (16G29)
clang --version (same as clang++ --version)
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
I have released the binaries for this on my builds (I still use the Linux binaries)

https://github.com/muschellij2/ITKR/releases
https://github.com/muschellij2/ANTsRCore/releases
https://github.com/muschellij2/ANTsR/releases

May be relevant to @jeffduda, @ntustison, @stnava

**Comment by stnava** [comment]
may be possible to set PKG_LIBS specifically for osx?  yes or no?


brian

**Comment by muschellij2** [comment]
Yes - but unsure how to use in configure, but def can do on Travis.

John

**Comment by muschellij2** [comment]
These are now covered in travis script and I have access to tag releases in ANTsRCore and ANTsR (but not ITKR)
