### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by jeffduda** [ANTsX/ANTsRCore#46]
Elegant handling of errors seems to be a persistent issue. For reasons that aren't clear to me Rcpp::stop() often seems to result in getting booted out of R which is really the worst case scenario. I think it would be beneficial if we could come up with consistent system for handling errors when they occur in the underlying C++ with an emphasis on stability. Perhaps something along the lines of:
1) When an exception is caught, print exception info and possibly additional info if known
2) return NULL (as opposed to NA which sometimes happens now)
3) All R wrapper code should check for NULL return and then call stop()

Open to other ideas & happy to help implement.

**Comment by stnava** [comment]
great idea.   so NULL=EXIT_FAILURE?   NA is a valid return value.   makes sense to me.  

do you have any ideas about how we can find all/most of the potential sources for these issues?

**Comment by jeffduda** [comment]
Yeah, NULL=EXIT_FAILURE is exactly what I had in mind. As for finding the potential sources, my guess is the the large majority can be found by searching for:
1) return(Rcpp::wrap(NA_REAL))
2) Rcpp::stop
I try to take a look this upcoming week and try to get a feel for how much effort would be needed to implement this.
