### ISSUE TITLE
Failing to read Images anymore

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#47]
I can't read in images that I could in the previous version:
[data.zip](https://github.com/ANTsX/ANTsRCore/files/2018110/data.zip)

These 
```r
antsImageRead("T1_N4_noneck_reduced_winsor_regtoFLAIR_brain_N4.nii.gz")
```
```
libc++abi.dylib: terminating with uncaught exception of type Rcpp::exception: Invalid pixel type in image header
Abort trap: 6
```

Fails at: https://github.com/ANTsX/ANTsRCore/blob/master/src/antsImageHeaderInfo.cpp#L91
Data type is (according to FSL): `data_type      FLOAT32`

This works fine:
```r
RNifti:::readNifti("T1_N4_noneck_reduced_winsor_regtoFLAIR_brain_N4.nii.gz")
```
as does

```r
neurobase::readnii("T1_N4_noneck_reduced_winsor_regtoFLAIR_brain_N4.nii.gz")
```

```r
 ANTsRCore * 0.5.0       2018-05-11 Github (stnava/ANTsRCore@9026770) 
```

**Comment by stnava** [comment]
You probably need to update your version of antsrcore

**Comment by muschellij2** [comment]
Updated and re-ran.  Reads in Images.
