### ISSUE TITLE
HDF5 errors

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#63]
Getting problems with HDF5 with current build of ITKR:
HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 0:
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/RtmpG4PrqY/devtools130da3d45a07a/stnava-ITKR-b7fd421/src/itks/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1400 in itk_H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file

Installed from @stnava ITKR branch.  Mya need to change ITK commit again.

**Comment by muschellij2** [comment]
See https://travis-ci.org/ANTsX/ANTsRCore/jobs/440065436#L2468.  I think this is due to the new ITK build, but I don't know why this is happening as we're not building shared libraries.  This happens as well if we install both from source locally.  Can you confirm @ntustison @stnava ?

**Comment by stnava** [comment]
i do see this issue on ubuntu18.04 but it does not produce an error.

the image reads fine though the same message is shown.

**Comment by muschellij2** [comment]
Gone in the new build
