### ISSUE TITLE
Interesting warning

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#65]
Getting this with current workflow:

```
WARNING: In /Users/johnmuschelli/Dropbox/Packages/ANTsRCore/src/ants/ImageSegmentation/antsGaussianListSampleFunction.hxx, line 122
GaussianListSampleFunction (0x7f9f63c4c560): The input list sample has <= 1 element.  Function evaluations will be equal to 0.

WARNING: In /Users/johnmuschelli/Dropbox/Packages/ANTsRCore/src/ants/ImageSegmentation/antsGaussianListSampleFunction.hxx, line 122
GaussianListSampleFunction (0x7f9f5b5d02f0): The input list sample has <= 1 element.  Function evaluations will be equal to 0.
```

**Comment by stnava** [comment]
pretty sure this is already fixed but what generates this, specifically?

**Comment by muschellij2** [comment]
Running abpN4
John

**Comment by stnava** [comment]
i dont see the warning - suspect it's fixed

**Comment by vnckppl** [comment]
I am receiving the same error when running Atropos on 20 out of 70 subjects. 

> WARNING: In .../ANTS_code/ANTsX-ANTs-7e85d85/ImageSegmentation/antsGaussianListSampleFunction.hxx, line 122

I am running ANTs on Debian 9.1 stretch with ANTs freshly compiled (--branch v2.3.1).

Any suggestions?
