### ISSUE TITLE
Potentially removing `colormap`

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsRCore#74]
So `colormap` requires `V8` which requires a 3rd party install of `v8` on machine.  Probably going to cause some headaches downstream for installers. Maybe use the `viridis` package if wanting that palette? https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html.  Or you can use `colorRampPalette` or `colorRamp`.

**Comment by muschellij2** [comment]
It's a heavy dependency for https://github.com/ANTsX/ANTsRCore/blob/master/R/plot.antsImage.R#L383 https://github.com/ANTsX/ANTsRCore/blob/master/R/plot.antsImage.R#L414

**Comment by stnava** [comment]
Closed by removing these dependencies.
